ProjetoModelo.MVC/Controllers/ClientesController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using ProjetoModelo.Application.Interfaces;
using ProjetoModelo.Application.ViewModels;

namespace ProjetoModelo.MVC.Controllers
{
    public class ClientesController : Controller
    {
        private readonly IClienteAppService _clienteApp;
        private readonly IEstadoAppService _estadoApp;
        private readonly ICidadeAppService _cidadeApp;
        private readonly IEnderecoAppService _enderecoApp;

        public ClientesController(
            IClienteAppService clienteApp, 
            IEstadoAppService estadoApp, 
            ICidadeAppService cidadeApp, 
            IEnderecoAppService enderecoApp)
        {
            _clienteApp = clienteApp;
            _estadoApp = estadoApp;
            _cidadeApp = cidadeApp;
            _enderecoApp = enderecoApp;
        }

        // GET: Cliente
        public ViewResult Index(string pesquisa, int page = 0)
        {
            var clienteViewModel = _clienteApp.ObterClientesGrid(page * 5, pesquisa);
            ViewBag.PaginaAtual = page;
            ViewBag.Pesquisa = pesquisa;
            ViewBag.TotalRegistros = _clienteApp.ObterTotalRegistros(pesquisa);


            return View(clienteViewModel);
        }


        // GET: Cliente/Details/5
        public ActionResult Details(Guid id)
        {
            var clienteViewModel = _clienteApp.GetById(id);

            return View(clienteViewModel);
        }

        // GET: Cliente/Create
        public ActionResult Create()
        {
            ViewBag.EstadoId = new SelectList(_estadoApp.GetAll().OrderBy(e => e.Nome), "EstadoId", "Nome");
            ViewBag.CidadeId = new SelectList(_cidadeApp.GetAll().OrderBy(c => c.Nome), "CidadeId", "Nome");

            return View();
        }

        // POST: Cliente/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ClienteEnderecoViewModel clienteEndereco)
        {
            ViewBag.EstadoId = new SelectList(_estadoApp.GetAll().OrderBy(e => e.Nome), "EstadoId", "Nome", clienteEndereco.EstadoId);
            ViewBag.CidadeId = new SelectList(_cidadeApp.GetAll().OrderBy(c => c.Nome), "CidadeId", "Nome", clienteEndereco.CidadeId);

            if (ModelState.IsValid)
            {
                var result = _clienteApp.Add(clienteEndereco);

                if (!result.IsValid)
                {
                    foreach (var validationAppError in result.Erros)
                    {
                        ModelState.AddModelError(string.Empty, validationAppError.Message);
                    }
                    return View(clienteEndereco);
                }

                return RedirectToAction("Index");
            }
     
            return View(clienteEndereco);
        }

        // GET: Cliente/Edit/5
        public ActionResult Edit(Guid id)
        {
            var clienteViewModel = _clienteApp.GetById(id);

            return View(clienteViewModel);
        }

        // POST: Cliente/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ClienteViewModel clienteViewModel)
        {
            if (ModelState.IsValid)
            {
                _clienteApp.Update(clienteViewModel);

                return RedirectToAction("Index");
            }

            return View(clienteViewModel);
        }

        // GET: Cliente/Delete/5
        public ActionResult Delete(Guid id)
        {
            var clienteViewModel = _clienteApp.GetById(id);

            return View(clienteViewModel);
        }

        // POST: Cliente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            var cliente = _clienteApp.GetById(id);
            _clienteApp.Remove(cliente);

            return RedirectToAction("Index");
        }
    }
}

ProjetoModelo.MVC/Controllers/VendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ProjetoModelo.Application.Interfaces;
using ProjetoModelo.Application.ViewModels;

namespace ProjetoModelo.MVC.Controllers
{
    public class VendaController : Controller
    {
        private readonly IProdutoAppService _produtoAppService;
        private readonly IClienteAppService _clienteAppService;
        private readonly IVendaAppService _vendaAppService;

        public VendaController(
            IProdutoAppService produtoAppService, 
            IClienteAppService clienteAppService, 
            IVendaAppService vendaAppService)
        {
            _produtoAppService = produtoAppService;
            _clienteAppService = clienteAppService;
            _vendaAppService = vendaAppService;
        }

        // GET: Venda
        public ActionResult Index()
        {
            ViewBag.ClienteId = new SelectList(_clienteAppService.GetAll(), "ClienteId", "Nome");
 
            return View(_produtoAppService.GetAll());
        }

        public ActionResult ProdutosVendidos()
        {
            return View(_vendaAppService.GetAll());
        }

        [HttpPost]
        public ActionResult Venda(FormCollection collection)
        {
            var ClienteId = collection["ClienteId"].Split(',').First();
            var Produtos = collection["produtos"].Split(',');

            foreach (var produtoItem in Produtos)
            {
                var produto = _produtoAppService.GetById(Guid.Parse(produtoItem));

                var venda = new VendaViewModel
                {
                    ClienteId = Guid.Parse(ClienteId),
                    ProdutosList = new List<ProdutoViewModel> { produto },
                    TipoVenda = TipoVendaViewEnum.Vista,
                    Valor = produto.Valor
                };

                _vendaAppService.Add(venda);
            }

            return View("ProdutosVendidos", _vendaAppService.GetAll());
        }
    }
}

ProjetoModelo.MVC/Views/Clientes/Create.cshtml
@model ProjetoModelo.Application.ViewModels.ClienteEnderecoViewModel

@{
    ViewBag.Title = "Cadastrar novo cliente";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sobrenome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sobrenome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Ativo)
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        
        <h4>Endereço</h4>
        <hr />
        @Html.Partial("_Endereco")

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoModelo.MVC/Views/Clientes/Delete.cshtml
@model ProjetoModelo.Application.ViewModels.ClienteViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClienteViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.CPF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CPF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjetoModelo.MVC/Views/Clientes/Details.cshtml
@model ProjetoModelo.Application.ViewModels.ClienteViewModel

@{
    ViewBag.Title = "Detalhes do Cliente";
}

<h2>@ViewBag.Title</h2>

<div>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CPF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CPF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new {id = Model.ClienteId}) |
    @Html.ActionLink("Back to List", "Index")
</p>

<h2>Endereços do Cliente</h2>

@RenderPage("EnderecosCliente.cshtml", Model)

@section scripts
{

    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.4/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/9dcbecd42ad/integration/bootstrap/3/dataTables.bootstrap.css">

    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.4/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/plug-ins/9dcbecd42ad/integration/bootstrap/3/dataTables.bootstrap.js"></script>

    <script type="text/javascript">

        $(document).ready(function() {
            $('#enderecosJson').dataTable({
                dom: "rtils",
                "bServerSide": true,
                "sAjaxDataProp": "aaData",
                "bProcessing": true,
                "bLengthChange": false,
                "aoColumns": [
                    {
                        "mData": "Rua",
                        "bSearchable": false,
                        "bSortable": false
                    },
                    {
                        "mData": "Numero",
                        "bSearchable": false,
                        "bSortable": false
                    },
                    {
                        "mData": "Complemento",
                        "bSearchable": false,
                        "bSortable": false
                    },
                    {
                        "mData": "Bairro",
                        "bSearchable": false,
                        "bSortable": false
                    },
                    {
                        "mData": "CEP",
                        "bSearchable": false,
                        "bSortable": false
                    },
                    {
                        "mData": "Estado",
                        "bSearchable": false,
                        "bSortable": false
                    },
                    {
                        "mData": "Cidade",
                        "bSearchable": false,
                        "bSortable": false
                    }
                ],
                "sAjaxSource": 'http://localhost:26669/api/clientes/@Model.ClienteId'
            });
        });

        $('#enderecosJson')
            .removeClass('table')
            .addClass('table table-striped table-bordered');
    </script>

}

ProjetoModelo.MVC/Views/Clientes/Edit.cshtml
@model ProjetoModelo.Application.ViewModels.ClienteViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ClienteViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ClienteId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sobrenome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sobrenome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sobrenome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Ativo)
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoModelo.MVC/Views/Clientes/EnderecosCliente.cshtml
@*@model ProjetoModelo.Application.ViewModels.ClienteViewModel
@{        
    if (Model.Enderecos.Any())
    {
        var endereco = Model.Enderecos.First();
        <table id="enderecos" class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => endereco.Rua)
                </th>
                <th>
                    @Html.DisplayNameFor(model => endereco.Numero)
                </th>
                <th>
                    @Html.DisplayNameFor(model => endereco.Complemento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => endereco.Bairro)
                </th>
                <th>
                    @Html.DisplayNameFor(model => endereco.CEP)
                </th>
                <th>
                    @Html.DisplayName("Estado")
                </th>
                <th>
                    @Html.DisplayName("Cidade")
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.Enderecos)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Rua)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Numero)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Complemento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Bairro)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CEP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Estado.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cidade.Nome)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new {id = item.EnderecoId}) |
                        @Html.ActionLink("Details", "Details", new {id = item.EnderecoId}) |
                        @Html.ActionLink("Delete", "Delete", new {id = item.EnderecoId})
                    </td>
                </tr>
            }

        </table>
    }
}*@

@Html.ActionLink("Adicionar Endereço", "CreateEndereco", "Clientes")

<table id="enderecosJson">
    <thead>
        <tr>
            <th>Rua</th>
            <th>Numero</th>
            <th>Complemento</th>
            <th>Bairro</th>
            <th>CEP</th>
            <th>Estado</th>
            <th>Cidade</th>
        </tr>
    </thead>
</table>                   

ProjetoModelo.MVC/Views/Clientes/Index.cshtml
@model IEnumerable<ProjetoModelo.Application.ViewModels.ClienteViewModel>

@{
    ViewBag.Title = "Clista de Clientes";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Adicionar Cliente", "Create")
</p>

@using (Html.BeginForm("Index", "Clientes", new {pesquisa = ""}, FormMethod.Get))
{
    <p>
        Pesquisar por nome: @Html.Editor("pesquisa") <input type="submit" value="Pesquisar" class="btn btn-default" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ativo)
        </th>
        <th></th>
        <th>Realizar Compras</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sobrenome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ativo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id = item.ClienteId}) |
                @Html.ActionLink("Details", "Details", new {id = item.ClienteId}) |
                @Html.ActionLink("Delete", "Delete", new {id = item.ClienteId})
            </td>
            <td>
                <a href="@Url.Action("Index", "Venda", new {cliente = item.ClienteId})">Selecionar</a>
            </td>
        </tr>
    }
</table>

@Html.Partial("_Paginacao")

ProjetoModelo.MVC/Views/Clientes/_Endereco.cshtml
@model ProjetoModelo.Application.ViewModels.ClienteEnderecoViewModel
@{
       
     <div class="form-group">
        @Html.LabelFor(model => model.Rua, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Rua, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(model => model.Rua, "", new {@class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Numero, htmlAttributes: new {@class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.EditorFor(model => model.Numero, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(model => model.Numero, "", new {@class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Complemento, htmlAttributes: new {@class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.EditorFor(model => model.Complemento, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(model => model.Complemento, "", new {@class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Bairro, htmlAttributes: new {@class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.EditorFor(model => model.Bairro, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(model => model.Bairro, "", new {@class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CEP, htmlAttributes: new {@class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.EditorFor(model => model.CEP, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(model => model.CEP, "", new {@class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EstadoId, htmlAttributes: new {@class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.DropDownList("EstadoId", (IEnumerable<SelectListItem>)ViewBag.EstadoId, String.Empty, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.ValidationMessageFor(model => model.EstadoId, "", new {@class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CidadeId, htmlAttributes: new {@class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.DropDownList("CidadeId", (IEnumerable<SelectListItem>)ViewBag.CidadeId, String.Empty, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.ValidationMessageFor(model => model.CidadeId, "", new {@class = "text-danger"})
        </div>
    </div>
}

ProjetoModelo.MVC/Views/Clientes/_Paginacao.cshtml
<nav>
    <ul class="pagination">
        <li>
            <a href="#" aria-label="Anterior">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        @for(var i = 0; i <= (ViewBag.TotalRegistros/5); i++)
        {
            <li><a class="@(i == ViewBag.PaginaAtual ? "current" : "")" href="@Url.Action("Index", "Clientes", new { page = i, pesquisa = ViewBag.Pesquisa })">@i</a></li>
        }
        <li>
            <a href="#" aria-label="Próximo">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>